### ISSUE TITLE
DB 모델 가이드라인 생성

### ISSUE THREAD

**Issue by 2unbini** [2unbini/42votes#1]
gpark 의 aquery를 통한 모델 생성
그리고 해당 내용 ekwon과 상의 후 결정

**Comment by ParkGunWook** [comment]
![okvotes_20211122_203431](https://user-images.githubusercontent.com/18071337/142854860-bf4a92f7-22e0-4f23-89c9-272c24fd6a39.png)

**Comment by ParkGunWook** [comment]
![okvotes_20211124_145907](https://user-images.githubusercontent.com/18071337/143183220-cce4cb0b-f6aa-4e60-bec4-2e5d0df23cfd.png)

question table에 is_expired를 추가했습니다.
