### ISSUE TITLE
Date 포맷 일치시키기.

### ISSUE THREAD

**Issue by ParkGunWook** [2unbini/42votes#19]
현재의 "yyyy-MM-dd'T'HH:mm:ssZZZZZ" 양식이 잘 작동하지 않을 시에, timeIntervalSinceReferenceDate로 변경.

**Comment by 2unbini** [comment]
- yyyy-MM-dd'T'HH:mm:ss
- yyyy-MM-dd'T'HH:mm:ss'Z'

두 포맷 모두 정상적으로 작동
