### ISSUE TITLE
UI 가이드라인 생성

### ISSUE THREAD

**Issue by 2unbini** [2unbini/42votes#2]
Figma로 UI 가이드라인 생성하기
구체적인 화면은 회의 후 결정

**Comment by 2unbini** [comment]
<img width="861" alt="스크린샷 2021-11-21 오후 6 44 39" src="https://user-images.githubusercontent.com/75126613/142757187-ed67bbec-e8b4-4493-be3e-0ca4889d729b.png">

**Comment by 2unbini** [comment]
https://www.figma.com/file/szD6ZHctx8ISpb9klmzc3B/42votes?node-id=0%3A1

**Comment by ParkGunWook** [comment]
![Screenshot_20211123-144418](https://user-images.githubusercontent.com/18071337/142976517-2b9bdf62-aefd-4b77-a6e3-2d86421f0f7b.jpg)

**Comment by 2unbini** [comment]
<img width="918" alt="storyboard" src="https://user-images.githubusercontent.com/75126613/143183810-321d405e-ca3e-4d2a-ac11-b1d41de50d55.png">

- Apple ID로 로그인 추가
- 둘러보기 버튼 추가
- My Page 로그인 페이지 추가
- Closed 페이지 추가
